### ISSUE TITLE
[BUG] Logging in succeeds but in but throws error

### ISSUE THREAD

**Issue by vivekt** [nishad/udemy-dl#206]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

[BUG] Logging in succeeds but in but throws error

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{ [BUG] Logging in succeeds but in but throws error }

C:\udemy-dl-win>udemy-dl.exe -u myAcc@yahoo.com -p myPass https://www.udemy.com/ninafochcourse

throws the following order

[INFO-884] Downloading to: C:\udemy-dl-win\ninafochcourse

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 33949
[ERROR-1198] Traceback (most recent call last):
File "", line 889, in
File "", line 886, in main
File "", line 705, in udemy_dl
File "", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1

Please help

Thanks and regards

Vivek

**Comment by diridou** [comment]
I have exactly the same problem

**Comment by DannyFeliz** [comment]
Same error here!

**Comment by MoCityMM** [comment]
**Getting something slightly different, when I run it I get the following (on Windows 7):**

_Traceback (most recent call last):
  File "logging\__init__.py", line 870, in emit
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
LookupError: unknown encoding: cp65001
Logged from file __init__.py, line 1198
udemy_dl returned -1_

**So I decided to pipe the error to text file to post and get this:**

Username / Email :  (which I don't get at the command shell)

**I terminate the process and get this:**

Traceback (most recent call last):
  File "logging\__init__.py", line 870, in emit
LookupError: unknown encoding: cp65001
Logged from file __init__.py, line 1198
udemy_dl returned -1

**Which is pretty much the same as the error via the command shell**

**Comment by ngdaniel1** [comment]
Windows 10.

This is my first attempt using your software. I received a similar error.  The command line would start and end in a flash and disappear.  There wasn't a way to capture an image.  

Using the Power Shell, I entered, ".\udemy-dl https://www.udemy.com/hedge-fund-startup/"
Username: [E-mail]
Password: [Password]

Trying to log in …
Login success.
Found course id: 1057242
Found course title: Learn How to Set Up an Incubator Hedge Fund – Step-by-Step
Exception
Traceback (most recent call last):
File “udemy_dl.py”, line 976, in
File “udemy_dl.py”, line 971, in main
File “udemy_dl.py”, line 785, in udemy_dl
File “udemy_dl.py”, line 431, in get_data_links
KeyError: u’results’
Failed to execute script udemy_dl


I hope this is enough details for you to figure out a solution.  If not, you'll have to guide me on where to get more because this was all that appeared on the Power Shell.

Can you explain what went wrong?
Thanks.

**Comment by Puyodead1** [comment]
same here

**Comment by Puyodead1** [comment]
FIXED IT, unzip the udemy-dl zip to a differant folder, update it, and try

**Comment by diridou** [comment]
My version is O.2.1 and I still have this problem. I reinstalled udemy twice and updated it but it didn't work. 
Any ideas ?

**Comment by Rajan4436** [comment]
Same issue.

**Comment by Rajan4436** [comment]
However I faced this error only when I try to login using single command `udemy-dl -u user@domain.com -p $ecRe7w0rd https://www.udemy.com/COURSE_NAME.`

The script is fine if I skip inline username and password with `udemy-dl  https://www.udemy.com/COURSE_NAME`
